---
- hosts: all
  sudo: yes
  vars:
    app_name: app 
    webapps_dir: /opt/webapps
   
  handlers:
    - name: reload supervisor config
      command: supervisorctl reload && supervisorctl update

  tasks:
    - name: Update Server
      yum: 
        name=*
        state=latest
    
    - name: Install Python, Pip and Supervisor
      yum: state=present name={{ item }}
      with_items:
      - python
      - python-pip
      - supervisor

    - name: Install supervisor configuration
      template: >
        src=templates/flask_supervisor.conf
        dest=/etc/supervisord.d/flask_supervisor.ini
      notify: reload supervisor config

    - name: Start Supervisor
      service: 
        name=supervisord
        state=restarted

    - name: Create Webapp Dir
      file:
        path={{ webapps_dir }}
        state=directory
        mode=0755

    - name: Get Flask App
      copy: 
        src=app
        dest={{ webapps_dir }}/{{ app_name }}
        owner=vagrant
        group=vagrant
        mode=0755

    - name: Install Pip Requirements
      pip: 
        requirements={{ webapps_dir }}/{{ app_name }}/app/requirements.txt 
    
    - name: Start Flask App
      supervisorctl: 
        name=app 
        state=restarted
